import { test, expect, type Page } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { model } from '../server/model.js';
async function openExplorer(page: Page) {
  await page.goto('/');
  await expect(page.getByRole('navigation', { name: 'Vistas' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Acceder', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Cerrar sesion', exact: true })).toHaveCount(0);
  await expect(page.locator('.records-table tbody tr')).toHaveCount(25);
}
async function view(page: Page, name: string) { await page.getByRole('navigation', { name: 'Vistas' }).getByRole('button', { name, exact: true }).click(); }
test('exploracion visual, filtros, fuentes y relaciones', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await openExplorer(page);
  await expect(page.getByRole('heading', { name: 'ciudadanos', exact: true })).toBeVisible();
  await expect(page.locator('.null-value').first()).toBeVisible();
  await page.screenshot({ path: `test-results/${info.project.name}-datos.png`, fullPage: true });
  await page.getByRole('button', { name: 'Ver registro 1', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByLabel('Buscar registros').pressSequentially('Laia', { delay: 60 });
  await expect(page.getByLabel('Buscar registros')).toHaveValue('Laia');
  await expect(page.locator('.records-table tbody tr')).toHaveCount(10);
  await page.getByLabel('Buscar registros').fill('');
  await expect(page.locator('.records-table tbody tr')).toHaveCount(25);
  await page.getByRole('button', { name: 'Pagina siguiente', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Ver registro 26', exact: true })).toBeVisible();
  await view(page, 'Estructura');
  await expect(page.locator('.schema-table tbody tr')).toHaveCount(model.padron.ciudadanos.fields.length);
  await view(page, 'Relaciones');
  await expect(page.locator('.react-flow__node')).toHaveCount(5);
  await expect(page.locator('.react-flow__edge')).toHaveCount(4);
  await expect(page.locator('.react-flow__node').first()).toBeInViewport();
  await page.screenshot({ path: `test-results/${info.project.name}-relaciones.png`, fullPage: true });
  await view(page, 'Calidad');
  await expect(page.locator('.quality-table tbody tr')).toHaveCount(6);
  await expect(page.getByText('Comprobaciones locales;', { exact: false })).toBeVisible();
  await page.locator('.quality-table').getByRole('button', { name: '3', exact: true }).click();
  await expect(page.locator('.records-table tbody tr')).toHaveCount(1);
  await expect(page.getByRole('button', { name: 'Ver registro 3', exact: true })).toBeVisible();
  await view(page, 'Conexiones');
  await expect(page.getByText('host.docker.internal:55432', { exact: true })).toBeVisible();
  await expect(page.locator('.credentials-table')).toContainText(process.env.READER_PASSWORD!);
  for (const [name, table] of [['Tributos', 'liquidaciones'], ['Expedientes', 'expedientes']]) {
    await page.getByRole('navigation', { name: 'Fuentes', exact: true }).getByRole('button', { name: new RegExp(name) }).click();
    await view(page, 'Datos');
    await expect(page.getByRole('heading', { name: table, exact: true })).toBeVisible();
    await expect(page.locator('.records-table tbody tr')).toHaveCount(25);
    await view(page, 'Relaciones');
    await expect(page.locator('.external-node')).toBeVisible();
  }
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  expect(overflow).toBe(false);
  expect(errors).toEqual([]);
});
test('ejecucion, comparacion y restauracion desde la web', async ({ page }, info) => {
  await openExplorer(page); await view(page, 'Cambios');
  const run = async (name: string) => {
    await page.locator('.scenario').filter({ has: page.getByRole('heading', { name, exact: true }) }).getByRole('button', { name: 'Preparar' }).click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await page.getByRole('button', { name: 'Confirmar y ejecutar' }).click();
    await expect(page.getByRole('dialog')).not.toBeVisible({ timeout: 30000 });
    await expect(page.getByRole('status')).toBeVisible();
  };
  try {
    await run('Anadir 5 registros');
    await expect(page.getByRole('status')).toContainText('100 → 105');
    await run('Anadir columna');
    await expect(page.getByRole('status')).toContainText('canal_origen');
    await run('Cambiar tipo');
    await expect(page.getByRole('status')).toContainText('text');
    await page.screenshot({ path: `test-results/${info.project.name}-cambios.png`, fullPage: true });
  } finally { await run('Restaurar base'); }
  await view(page, 'Estructura');
  await expect(page.locator('.schema-table tbody tr')).toHaveCount(model.padron.ciudadanos.fields.length);
  await expect(page.locator('.schema-table')).not.toContainText('canal_origen');
});
test('acceso directo, CSRF y rechazo de SQL arbitrario', async ({ request, page }) => {
  const connections = await request.get('/api/connections');
  expect(connections.status()).toBe(200);
  expect((await connections.json()).web).not.toHaveProperty('password');
  await openExplorer(page);
  const session = await (await page.request.get('/api/session')).json();
  const body = { action: 'insert', requestId: randomUUID(), confirm: true };
  expect((await page.request.post('/api/db/padron/scenario', { data: body })).status()).toBe(403);
  const origin = new URL(page.url()).origin;
  expect((await request.post('/api/db/padron/scenario', { headers: { Origin: origin, 'X-CSRF-Token': session.csrf }, data: body })).status()).toBe(403);
  expect((await page.request.post('/api/db/padron/scenario', { headers: { Origin: 'http://otra-pagina.invalid', 'X-CSRF-Token': session.csrf }, data: body })).status()).toBe(403);
  expect((await page.request.post('/api/db/padron/scenario', { headers: { Origin: origin }, data: body })).status()).toBe(403);
  expect((await page.request.post('/api/db/padron/scenario', { headers: { Origin: origin, 'X-CSRF-Token': session.csrf }, data: { ...body, action: 'DROP DATABASE padron' } })).status()).toBe(400);
  expect((await page.request.get('/api/db/padron/table/_lab_state/rows')).status()).toBe(404);
  expect((await page.request.get('/api/db/padron/table/ciudadanos/rows?search=%27%3BDROP%20TABLE%20ciudadanos')).status()).toBe(200);
});
test('Escoles: web HTML, extraccion, escenarios y vistas responsivas', async ({ page, context }, info) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  const navigation = page.getByRole('navigation', { name: 'Fuentes', exact: true });
  await expect(navigation.getByRole('button')).toHaveCount(4);
  await navigation.getByRole('button', { name: /Escoles/ }).click();
  const session = await (await page.request.get('/api/session')).json();
  const headers = { Origin: new URL(page.url()).origin, 'X-CSRF-Token': session.csrf };
  const change = async (action: string, requestId = randomUUID()) => {
    const response = await page.request.post('/api/source/escoles/scenario', { headers, data: { action, requestId, confirm: true } });
    expect(response.status()).toBe(200);
    return response.json();
  };
  const run = async (name: string) => {
    await view(page, 'Cambios');
    await page.locator('.scenario').filter({ has: page.getByRole('heading', { name, exact: true }) }).getByRole('button', { name: 'Preparar' }).click();
    await expect(page.getByRole('dialog')).toContainText('tabla publicada');
    await page.getByRole('button', { name: 'Confirmar y ejecutar' }).click();
    await expect(page.getByRole('dialog')).not.toBeVisible();
    await expect(page.getByRole('status')).toBeVisible();
  };
  await change('reset');
  await page.getByRole('button', { name: 'Actualizar datos', exact: true }).click();
  const original = await context.newPage();
  original.on('pageerror', error => errors.push(error.message));
  const connection = (await (await page.request.get('/api/connections')).json()).html;
  try {
    await expect(page.getByRole('heading', { name: 'matriculas', exact: true })).toBeVisible();
    await expect(page.locator('.records-table tbody tr')).toHaveCount(20);
    await expect(page.locator('.html-provenance')).toContainText('#matriculas');
    await page.screenshot({ path: `test-results/${info.project.name}-escoles-datos.png`, fullPage: true });
    await original.goto(connection.url);
    await expect(original.getByRole('heading', { name: 'Escoles', exact: true })).toBeVisible();
    await expect(original.locator('#matriculas tbody tr')).toHaveCount(20);
    await expect(original.locator('img')).toHaveJSProperty('naturalWidth', 36);
    expect(await original.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
    await original.screenshot({ path: `test-results/${info.project.name}-escoles-web.png`, fullPage: true });
    await page.getByLabel('Buscar registros').fill('Laia');
    await expect(page.locator('.records-table tbody tr')).toHaveCount(2);
    await page.getByLabel('Buscar registros').fill('');
    await page.locator('.records-table th').first().getByRole('button').click();
    await expect(page.locator('.records-table tbody tr').first().locator('td').first()).toHaveText('1');
    await page.locator('.records-table th').first().getByRole('button').click();
    await expect(page.locator('.records-table tbody tr').first().locator('td').first()).toHaveText('20');
    await view(page, 'Estructura');
    await expect(page.locator('.schema-table tbody tr')).toHaveCount(13);
    await expect(page.locator('.schema-table')).toContainText('No declaradas');
    await expect(page.getByRole('heading', { name: 'Indices', exact: true })).toHaveCount(0);
    await view(page, 'Relaciones');
    await expect(page.locator('.react-flow__node')).toHaveCount(2);
    await expect(page.locator('.react-flow__edge')).toHaveCount(1);
    await expect(page.locator('.external-node')).toBeVisible();
    await view(page, 'Calidad');
    await expect(page.locator('.quality-table tbody tr')).toHaveCount(4);
    await expect(page.locator('.quality-summary')).toContainText('0incidencias locales');
    await view(page, 'Conexiones');
    await expect(page.getByRole('link', { name: 'Abrir Escoles', exact: true })).toHaveAttribute('href', connection.url);
    await expect(page.locator('.credentials-table')).toHaveCount(0);
    await run('Anadir 5 matriculas');
    await expect(page.getByRole('status')).toContainText('20 → 25');
    await run('Anadir 5 matriculas');
    await view(page, 'Datos');
    await expect(page.locator('.records-table tbody tr')).toHaveCount(25);
    await page.getByRole('button', { name: 'Pagina siguiente', exact: true }).click();
    await expect(page.locator('.records-table tbody tr')).toHaveCount(5);
    await run('Actualizar una matricula');
    await run('Anadir columna HTML');
    await expect(page.getByRole('status')).toContainText('beca');
    await run('Renombrar encabezado');
    await expect(page.getByRole('status')).toContainText('nivel');
    await expect(page.getByRole('status')).toContainText('Retirada');
    await view(page, 'Estructura');
    await expect(page.locator('.schema-table tbody tr')).toHaveCount(14);
    await expect(page.locator('.schema-table')).toContainText('nivel');
    await original.reload();
    await expect(original.locator('#matriculas tbody tr')).toHaveCount(30);
    await expect(original.locator('#matriculas th')).toHaveCount(14);
    await expect(original.getByRole('columnheader', { name: 'Nivel', exact: true })).toBeVisible();
    await expect(original.locator('#matriculas tbody tr').first()).toContainText('Escola Sant Pere');
    await page.screenshot({ path: `test-results/${info.project.name}-escoles-estructura.png`, fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
    await run('Restaurar web');
    await view(page, 'Datos');
    await expect(page.locator('.records-table tbody tr')).toHaveCount(20);
    await view(page, 'Cambios');
    await expect(page.locator('.history-list details').first()).toContainText('Restaurar web');
    const id = randomUUID();
    await change('update', id);
    expect((await change('update', id)).alreadyApplied).toBe(true);
    expect(errors).toEqual([]);
  } finally { await change('reset'); await original.close(); }
});
test('Escoles: seguridad, errores visibles y recuperacion', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('navigation', { name: 'Fuentes', exact: true }).getByRole('button', { name: /Escoles/ }).click();
  await expect(page.locator('.records-table tbody tr')).toHaveCount(20);
  const session = await (await page.request.get('/api/session')).json();
  const origin = new URL(page.url()).origin;
  const body = { action: 'insert', requestId: randomUUID(), confirm: true };
  expect((await page.request.post('/api/source/escoles/scenario', { data: body })).status()).toBe(403);
  expect((await page.request.post('/api/source/escoles/scenario', { headers: { Origin: 'http://otra.invalid', 'X-CSRF-Token': session.csrf }, data: body })).status()).toBe(403);
  expect((await page.request.post('/api/source/escoles/scenario', { headers: { Origin: origin, 'X-CSRF-Token': session.csrf }, data: { ...body, confirm: false } })).status()).toBe(400);
  expect((await page.request.post('/api/source/escoles/scenario', { headers: { Origin: origin, 'X-CSRF-Token': session.csrf }, data: { ...body, action: 'DROP TABLE' } })).status()).toBe(400);
  expect((await page.request.get('/api/source/otra/table/matriculas/rows')).status()).toBe(404);
  const route = '**/api/source/escoles/table/matriculas/rows?*';
  await page.route(route, async response => response.fulfill({ status: 502, contentType: 'application/json', body: JSON.stringify({ error: 'Escoles: la web no responde' }) }));
  await page.getByRole('button', { name: 'Actualizar datos', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('web no responde');
  await expect(page.locator('.records-table')).toHaveCount(0);
  await page.getByRole('navigation', { name: 'Fuentes', exact: true }).getByRole('button', { name: /Padron/ }).click();
  await expect(page.locator('.records-table tbody tr')).toHaveCount(25);
  await page.unroute(route);
  await page.getByRole('navigation', { name: 'Fuentes', exact: true }).getByRole('button', { name: /Escoles/ }).click();
  await expect(page.locator('.records-table tbody tr')).toHaveCount(20);
  await expect(page.getByRole('alert')).toHaveCount(0);
});