import { useEffect, useRef, useState } from 'react';
import { Database, Table2, Columns3, GitFork, ShieldCheck, FlaskConical, Plug, Search, RefreshCw, ChevronRight, ChevronLeft, ArrowUpDown, Copy, Check, Plus, Pencil, History, RotateCcw, Play, AlertTriangle, X, KeyRound, ExternalLink, Eye } from 'lucide-react';
import { ReactFlow, Background, Controls, MarkerType, type Node, type Edge } from '@xyflow/react';
type DbId = 'padron' | 'tributos' | 'expedientes' | 'escoles';
interface Db { id: DbId; label: string; engine: string; schema: string; port: number; status: string; type: 'database' | 'html'; defaultObject: string; capabilities: { indexes: boolean; physicalRelationships: boolean; changes: boolean }; tables: { name: string; kind: string; count: number }[]; initialCounts: Record<string, number> }
const tabs = [{ id: 'data', label: 'Datos', icon: Table2 }, { id: 'schema', label: 'Estructura', icon: Columns3 }, { id: 'relations', label: 'Relaciones', icon: GitFork }, { id: 'quality', label: 'Calidad', icon: ShieldCheck }, { id: 'changes', label: 'Cambios', icon: FlaskConical }, { id: 'connections', label: 'Conexiones', icon: Plug }];
const labels: Record<DbId, string> = { padron: 'Padron', tributos: 'Tributos', expedientes: 'Expedientes', escoles: 'Escoles' };
let csrf = '';
async function api(path: string, options: RequestInit = {}) {
  const response = await fetch(`/api${path}`, { ...options, headers: { ...(options.body ? { 'Content-Type': 'application/json', 'X-CSRF-Token': csrf } : {}), ...options.headers } });
  const payload = await response.json();
  if (!response.ok) throw new Error(payload.error || 'Servicio no disponible');
  return payload;
}
const post = async (path: string, body: unknown) => {
  const session = await api('/session');
  csrf = session.csrf;
  return api(path, { method: 'POST', body: JSON.stringify(body) });
};
function CopyValue({ value }: { value: string }) {
  const [copied, setCopied] = useState(false);
  return <span className="copy-value"><code>{value}</code><button className="icon-button" title={copied ? 'Copiado' : 'Copiar'} aria-label={`Copiar ${value}`} onClick={async () => { try { await navigator.clipboard.writeText(value); setCopied(true); } catch { setCopied(false); } }}>{copied ? <Check size={14} /> : <Copy size={14} />}</button></span>;
}
function Cell({ value }: { value: unknown }) {
  if (value === null) return <span className="null-value">NULL</span>;
  if (value === '') return <span className="empty-value">VACIO</span>;
  return <>{typeof value === 'object' ? JSON.stringify(value) : String(value)}</>;
}
function RelationshipGraph({ db, relationships, onTable }: { db: Db; relationships: any[]; onTable: (db: DbId, table: string) => void }) {
  const objects = db.tables.filter(table => table.kind !== 'VIEW');
  const nodes: Node[] = objects.map((table, index) => ({ id: table.name, position: { x: index % 3 * 260, y: Math.floor(index / 3) * 160 },
    data: { label: <div className="graph-label"><Table2 size={16} /><strong>{table.name}</strong><small>{table.count} registros</small></div> }, style: { width: 220, borderRadius: 6 } }));
  const edges: Edge[] = relationships.filter(relation => !relation.logical).map((relation, index) => ({ id: `fk-${index}`, source: relation.child, target: relation.parent, label: relation.column_name, markerEnd: { type: MarkerType.ArrowClosed }, type: 'smoothstep' }));
  if (db.id !== 'padron') {
    nodes.push({ id: 'padron.ciudadanos', position: { x: db.type === 'html' ? 280 : 520, y: db.type === 'html' ? 160 : 360 }, data: { label: <div className="graph-label external-node"><ExternalLink size={16} /><strong>padron.ciudadanos</strong><small>Relacion logica entre fuentes</small></div> }, style: { width: 220, borderRadius: 6, borderStyle: 'dashed' } });
    edges.push({ id: 'external', source: db.id === 'tributos' ? 'contribuyentes' : db.defaultObject, target: 'padron.ciudadanos', label: 'ciudadano_id (logica)', style: { strokeDasharray: '6 4' }, type: 'smoothstep' });
  }
  return <div className="graph-surface"><ReactFlow nodes={nodes} edges={edges} fitView fitViewOptions={{ padding: 0.18 }} minZoom={0.3} maxZoom={1.5} nodesDraggable={false} onNodeClick={(_, node) => node.id === 'padron.ciudadanos' ? onTable('padron', 'ciudadanos') : onTable(db.id, node.id)}><Background gap={24} /><Controls showInteractive={false} /></ReactFlow></div>;
}
export function App() {
  const [checking, setChecking] = useState(true);
  const [databases, setDatabases] = useState<Db[]>([]); const [dbId, setDbId] = useState<DbId>('padron');
  const [table, setTable] = useState('ciudadanos'); const [tab, setTab] = useState('data');
  const [loaded, setLoaded] = useState<any>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const viewKey = `${dbId}:${table}:${tab}`;
  const payload = loaded?.key === viewKey ? loaded.value : null;
  const setPayload = (value: any) => setLoaded(value === null ? null : { key: viewKey, value });
  const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [sort, setSort] = useState(''); const [direction, setDirection] = useState('asc');
  const [tableSearch, setTableSearch] = useState(''); const [revision, setRevision] = useState(0);
  const [confirmation, setConfirmation] = useState<any>(null); const [busy, setBusy] = useState(false); const [result, setResult] = useState<any>(null);
  const [selectedRow, setSelectedRow] = useState<any>(null); const [resetText, setResetText] = useState('');
  const lastQuery = useRef('');
  const db = databases.find(item => item.id === dbId);
  useEffect(() => { api('/session').then(session => { csrf = session.csrf; }).catch(failure => setError(failure.message)).finally(() => setChecking(false)); }, []);
  useEffect(() => {
    if (checking) return;
    const controller = new AbortController();
    api('/sources', { signal: controller.signal }).then(setDatabases).catch(failure => { if (failure.name !== 'AbortError') setError(failure.message); });
    return () => controller.abort();
  }, [checking, revision]);
  useEffect(() => {
    if (checking || !db) return;
    const controller = new AbortController();
    const key = `${dbId}:${table}:${tab}`;
    if (tab !== 'data' || lastQuery.current !== key) { setLoading(true); setPayload(null); }
    lastQuery.current = key;
    setError('');
    const options = { signal: controller.signal };
    const base = `/source/${dbId}`;
    const fetchPayload = async () => {
      if (tab === 'data') return api(`${base}/table/${encodeURIComponent(table)}/rows?${new URLSearchParams({ page: String(page), size: '25', search, sort, direction })}`, options);
      if (tab === 'schema') return api(`${base}/table/${encodeURIComponent(table)}/schema`, options);
      if (tab === 'relations') return api(`${base}/relationships`, options);
      if (tab === 'quality') return api(`${base}/quality`, options);
      if (tab === 'connections') return api('/connections', options);
      const [scenarios, history] = await Promise.all([api(`${base}/scenarios`, options), api(`${base}/history`, options)]);
      return { scenarios, history };
    };
    fetchPayload().then(setPayload).catch(failure => { if (failure.name !== 'AbortError') { setPayload(null); setError(failure.message); } }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [checking, dbId, Boolean(db), table, tab, page, search, sort, direction, revision]);
  function navigate(id: DbId, name?: string) {
    setDbId(id); setTable(name || databases.find(item => item.id === id)?.defaultObject || 'ciudadanos'); setPage(1); setSearch(''); setSort(''); setTableSearch(''); setResult(null); setSelectedRow(null);
    if (name) setTab('data');
  }
  async function execute() {
    setBusy(true); setError('');
    try {
      const next = confirmation.id === 'reset-all' ? await post('/reset', { confirm: resetText, requestId: confirmation.requestId }) : await post(`/source/${dbId}/scenario`, { action: confirmation.id, confirm: true, requestId: confirmation.requestId });
      setResult(next); setConfirmation(null); setResetText(''); setPage(1); setRevision(value => value + 1);
    } catch (failure) { setError((failure as Error).message); } finally { setBusy(false); }
  }
  const openConfirmation = (scenario: any) => { setConfirmation({ ...scenario, requestId: crypto.randomUUID() }); setResetText(''); };
  if (checking) return <div className="initial-loading">Veciana <span>Conectando...</span></div>;
  return <div className="app-shell" data-domain={dbId}>
    <header className="app-header"><div className="brand"><span className="brand-icon"><Database size={21} /></span><div><strong>Veciana<span className="brand-divider">/</span><span className="brand-lab">lab</span></strong><small>Laboratorio municipal del dato</small></div></div><div className="header-right"><span className="synthetic-badge">DATOS SINTETICOS</span></div></header>
    <aside className="sidebar"><div className="sidebar-label">FUENTES MUNICIPALES <span>{String(databases.length).padStart(2, '0')}</span></div><nav className="source-nav" aria-label="Fuentes">{databases.map(item => <button key={item.id} className={`source-button ${item.id === dbId ? 'active' : ''}`} onClick={() => navigate(item.id)}><span className={`source-dot ${item.id}`} /><span><strong>{item.label}</strong><small>{item.engine}</small></span><ChevronRight size={15} /></button>)}</nav><div className="sidebar-rule" /><div className="sidebar-label">OBJETOS <span>{db?.tables.length || 0}</span></div><label className="search-box sidebar-search"><Search size={15} /><input aria-label="Buscar tablas" placeholder="Buscar tabla..." value={tableSearch} onChange={event => setTableSearch(event.target.value)} /></label><nav className="table-nav" aria-label="Tablas">{db?.tables.filter(item => item.name.includes(tableSearch.toLowerCase())).map(item => <button title={item.name} key={item.name} className={item.name === table ? 'active' : ''} onClick={() => { navigate(dbId, item.name); }}><span>{item.kind === 'VIEW' ? <Eye size={14} /> : <Table2 size={14} />}</span><span className="table-nav-name">{item.name}</span><small>{item.count}</small></button>)}</nav><div className="sidebar-bottom"><span className={`status-dot ${db?.status === 'online' ? 'online' : 'offline'}`} />{db?.status === 'online' ? 'Fuente conectada' : 'Fuente no disponible'}<code>:{db?.port}</code></div></aside>
    <main className="workspace"><div className="breadcrumb"><span>Veciana</span><ChevronRight size={12} /><span>{db?.label}</span><ChevronRight size={12} /><code>{db?.schema}</code></div><div className="workspace-title"><div><div className="eyebrow">{db?.engine.toUpperCase()} <span className="title-status"><span className={`status-dot ${db?.status === 'online' ? 'online' : 'offline'}`} />{db?.status === 'online' ? 'CONECTADO' : 'NO DISPONIBLE'}</span></div><h1>{tab === 'data' || tab === 'schema' ? table : tabs.find(item => item.id === tab)?.label}</h1></div><div className="title-actions"><span className="table-count">{db?.tables.filter(item => item.kind !== 'VIEW').reduce((sum, item) => sum + item.count, 0) || 0}<small>filas de negocio</small></span>{db?.type === 'html' && <a className="icon-button" title="Abrir web Escoles" aria-label="Abrir web Escoles" href={`http://localhost:${db.port}/`} target="_blank" rel="noreferrer"><ExternalLink size={19} /></a>}<button className="icon-button" title="Actualizar datos" aria-label="Actualizar datos" disabled={loading || busy} onClick={() => setRevision(value => value + 1)}><RefreshCw size={19} className={loading ? 'spin' : ''} /></button></div></div>
      <nav className="view-tabs" aria-label="Vistas">{tabs.filter(item => item.id !== 'changes' || db?.capabilities.changes).map(item => <button key={item.id} className={tab === item.id ? 'active' : ''} onClick={() => { setTab(item.id); setSelectedRow(null); }}><item.icon size={16} /><span>{item.label}</span></button>)}</nav>
      {error && <div className="error" role="alert"><AlertTriangle size={17} />{error}<button title="Cerrar aviso" className="icon-button" onClick={() => setError('')}><X size={15} /></button></div>}
      {loading && <div className="loading-state"><RefreshCw className="spin" size={20} /><span>Consultando {db?.label}...</span></div>}
      {!loading && payload?.provenance && <div className="html-provenance"><code>{payload.provenance.selector}</code><span>HTML extraido {new Date(payload.provenance.extractedAt).toLocaleString('es-ES')}</span></div>}
      {!loading && payload && tab === 'data' && <section className="data-view"><div className="data-toolbar"><div className="object-summary"><Table2 size={17} /><strong>{payload.total}</strong><span>registros</span><span className="dot-separator">/</span><span>{payload.columns.length} columnas</span></div><label className="search-box"><Search size={16} /><input aria-label="Buscar registros" placeholder="Buscar registros..." value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} /></label></div><div className="table-scroll"><table className="records-table"><thead><tr>{payload.columns.map((column: any) => <th key={column.name}><button onClick={() => { setSort(column.name); setDirection(sort === column.name && direction === 'asc' ? 'desc' : 'asc'); setPage(1); }}>{column.primary_key && <KeyRound size={12} />}<span>{column.name}<small>{column.type}</small></span><ArrowUpDown size={12} /></button></th>)}<th>Detalle</th></tr></thead><tbody>{payload.rows.map((row: any, index: number) => <tr key={String(row.id ?? index)}>{payload.columns.map((column: any) => <td key={column.name}><Cell value={row[column.name]} /></td>)}<td><button className="icon-button" title="Ver registro" aria-label={`Ver registro ${row.id ?? index + 1}`} onClick={() => setSelectedRow(row)}><Eye size={16} /></button></td></tr>)}</tbody></table>{!payload.rows.length && <div className="empty-state">No hay registros que coincidan.</div>}</div><footer className="table-footer"><span>{payload.total ? (page - 1) * 25 + 1 : 0}-{Math.min(page * 25, payload.total)} de {payload.total}</span><div><button className="icon-button" title="Pagina anterior" aria-label="Pagina anterior" disabled={page === 1} onClick={() => setPage(value => value - 1)}><ChevronLeft size={17} /></button><code>{page} / {Math.max(1, Math.ceil(payload.total / 25))}</code><button className="icon-button" title="Pagina siguiente" aria-label="Pagina siguiente" disabled={page * 25 >= payload.total} onClick={() => setPage(value => value + 1)}><ChevronRight size={17} /></button></div></footer></section>}
      {!loading && payload && tab === 'schema' && <section>
        <div className="section-heading"><h2>Columnas</h2><span>{payload.columns.length} campos</span></div>
        <div className="table-scroll"><table className="schema-table"><thead><tr><th>Columna</th><th>{payload.observed ? 'Tipo observado' : 'Tipo actual'}</th><th>{payload.observed ? 'Restricciones' : 'Nulabilidad'}</th><th>{payload.observed ? 'Encabezado HTML' : 'Descripcion'}</th></tr></thead><tbody>{payload.columns.map((column: any) => <tr key={column.name}><td><span className="field-name">{column.primary_key ? <KeyRound size={14} /> : <Columns3 size={14} />}<code>{column.name}</code></span></td><td><code className="type-value">{column.type}</code></td><td>{payload.observed ? 'No declaradas' : column.nullable ? 'NULL permitido' : 'NOT NULL'}</td><td>{column.description || <span className="muted">Sin descripcion</span>}</td></tr>)}</tbody></table></div>
        {db?.capabilities.indexes && <><div className="section-heading"><h2>Indices</h2><span>{payload.indexes.length}</span></div><div className="index-list">{payload.indexes.map((index: any, offset: number) => <div key={offset}><KeyRound size={15} /><code>{index.name}</code><span>{index.definition}{index.column_name ? ` (${index.column_name})` : ''}</span></div>)}</div></>}
      </section>}
      {!loading && payload && tab === 'relations' && db && <section><div className="section-heading"><h2>Mapa de relaciones</h2><div className="graph-legend">{db.capabilities.physicalRelationships && <><span className="legend-solid" />FK fisica</>}<span className="legend-dashed" />Relacion logica</div></div><RelationshipGraph db={db} relationships={payload} onTable={navigate} /><div className="section-heading"><h2>{db.capabilities.physicalRelationships ? 'Claves foraneas' : 'Relaciones declaradas'}</h2><span>{payload.length}</span></div><div className="relationship-list">{payload.map((relation: any, index: number) => <div key={index}><code>{relation.child}.{relation.column_name}</code><ChevronRight size={14} /><code>{relation.parent}.{relation.parent_column}</code></div>)}</div></section>}
      {!loading && payload && tab === 'quality' && <section><div className="quality-summary"><div><strong>{payload.rules.reduce((sum: number, rule: any) => sum + rule.failed.length, 0)}</strong><span>incidencias locales</span></div><div><strong>{payload.rules.length}</strong><span>reglas evaluadas</span></div><div><strong>{payload.rules.filter((rule: any) => rule.matchesExpected).length}/{payload.rules.length}</strong><span>coinciden con el escenario inicial</span></div></div><div className="notice"><ShieldCheck size={17} /><span>{payload.source}. Fecha de referencia: {payload.referenceDate}.{payload.legitimateMissingDocuments > 0 && ` ${payload.legitimateMissingDocuments} menores sin documento, ausencia prevista.`}</span></div><div className="table-scroll"><table className="quality-table"><thead><tr><th>Regla</th><th>Objeto</th><th>Registros afectados</th><th>Escenario inicial</th></tr></thead><tbody>{payload.rules.map((rule: any) => <tr key={rule.rule}><td><strong>{rule.description}</strong><small>{rule.rule}</small></td><td><code>{rule.table}.{rule.column}</code></td><td>{rule.failed.length ? rule.failed.map((id: number) => <button className="record-link" key={id} onClick={() => { navigate(dbId, rule.table); setSearch(`#${id}`); }}>{id}</button>) : <Check size={16} />}</td><td><span className={`state-label ${rule.matchesExpected ? 'success' : 'warning'}`}>{rule.matchesExpected ? 'Esperado' : 'Ha cambiado'}</span></td></tr>)}</tbody></table></div></section>}
      {!loading && payload && tab === 'changes' && <section>
        <div className="section-heading"><h2>Escenarios de prueba</h2><button className="text-button danger" onClick={() => openConfirmation({ id: 'reset-all', label: 'Restaurar todas las fuentes', detail: 'Restauracion secuencial de cuatro fuentes. Puede producir fallos parciales.', preview: 'Restaurar Padron, Tributos, Expedientes y la web Escoles al conjunto inicial.' })}><RotateCcw size={15} />Restaurar todo</button></div>
        <div className="scenario-grid">{payload.scenarios.map((scenario: any) => { const Icon = scenario.id === 'insert' ? Plus : scenario.id === 'update' ? Pencil : scenario.id === 'reset' ? RotateCcw : scenario.id === 'workload' ? Play : Columns3; return <article className={`scenario ${scenario.id === 'reset' ? 'reset-scenario' : ''}`} key={scenario.id}><div className="scenario-top"><Icon size={22} /><span className="eyebrow">{scenario.effect}</span></div><h3>{scenario.label}</h3><p>{scenario.detail}</p><button className="text-button" disabled={busy} onClick={() => openConfirmation(scenario)}>Preparar<ChevronRight size={16} /></button></article>; })}</div>
        {result && <div className="result-panel" role="status"><div className="section-heading"><h2><Check size={17} />{result.alreadyApplied ? 'Cambio ya aplicado' : 'Operacion completada'}</h2></div>{Array.isArray(result) ? result.map(item => <p key={item.db}>{labels[item.db as DbId]}: {item.success ? 'restaurada' : item.error}</p>) : <>
          <p><code>{result.after.table}</code>: {result.before?.count ?? '?'} → {result.after.count} filas</p>
          <div className="schema-diff">{result.after.columns.filter((column: any) => !result.before?.columns.some((old: any) => old.name === column.name && old.type === column.type)).map((column: any) => <div key={column.name}><Plus size={14} /><code>{column.name}</code><strong>{column.type}</strong></div>)}{result.before?.columns.filter((column: any) => !result.after.columns.some((next: any) => next.name === column.name)).map((column: any) => <div key={column.name}><X size={14} /><code>{column.name}</code><span>Retirada</span></div>)}</div>
          <code className="sql-inline">{result.sql || result.preview}</code>
        </>}</div>}
        <div className="section-heading"><h2><History size={17} />Bitacora</h2><span>Ultimas 50 operaciones</span></div><div className="history-list">{payload.history.length === 0 ? <div className="empty-state">Sin cambios registrados.</div> : payload.history.map((item: any) => <details key={item.request_id}><summary><span className={`history-dot ${item.status === 'done' ? 'success' : 'warning'}`} /><strong>{payload.scenarios.find((scenario: any) => scenario.id === item.action)?.label || item.action}</strong><span>{item.status}</span><time>{new Date(item.created_at).toLocaleString('es-ES')}</time></summary><pre>{JSON.stringify(item.result, null, 2)}</pre></details>)}</div>
      </section>}
      {!loading && payload && tab === 'connections' && <section>
        <div className="notice"><AlertTriangle size={17} /><span>{db?.type === 'html' ? 'Web sintetica de acceso local, sin autenticacion. No utilizar datos reales ni publicar este entorno.' : 'Credenciales del laboratorio. Exposicion local; no utilizar datos reales ni publicar este entorno.'}</span></div>
        {db?.type === 'html' && <><div className="section-heading"><h2>Web HTML</h2><a className="text-button" href={payload.html.url} target="_blank" rel="noreferrer"><ExternalLink size={15} />Abrir Escoles</a></div><div className="connection-grid"><div><small>URL DESDE WINDOWS</small><CopyValue value={payload.html.url} /></div><div><small>SELECTOR DE LA TABLA</small><CopyValue value={payload.html.selector} /></div></div></>}
        {payload.databases.filter((item: any) => item.id === dbId).map((item: any) => <div key={item.id}><div className="section-heading"><h2>{item.engine}</h2><span>{item.id} / {item.schema}</span></div><div className="connection-grid"><div><small>DESDE WINDOWS</small><CopyValue value={`localhost:${item.port}`} /></div><div><small>DESDE OPENMETADATA EN DOCKER</small><CopyValue value={`host.docker.internal:${item.port}`} /></div><div><small>RED INTERNA DE COMPOSE</small><CopyValue value={`${item.id}:${item.internalPort}`} /></div><div><small>BASE DE DATOS / SCHEMA</small><CopyValue value={`${item.id} / ${item.schema}`} /></div></div><div className="section-heading"><h2>Usuarios y permisos</h2><KeyRound size={17} /></div><div className="table-scroll"><table className="credentials-table"><thead><tr><th>Cuenta</th><th>Usuario</th><th>Contrasena</th></tr></thead><tbody>{item.accounts.map((account: any) => <tr key={account.role}><td>{account.role}</td><td><CopyValue value={account.username} /></td><td><CopyValue value={account.password} /></td></tr>)}</tbody></table></div></div>)}
        <div className="section-heading"><h2>Todos los puertos</h2><Plug size={17} /></div><div className="port-list">{payload.databases.map((item: any) => <button key={item.id} onClick={() => navigate(item.id)}><span className={`source-dot ${item.id}`} /><strong>{labels[item.id as DbId]}</strong><code>{item.port} → {item.internalPort}</code><ChevronRight size={15} /></button>)}<button onClick={() => navigate('escoles')}><span className="source-dot escoles" /><strong>Escoles</strong><code>{payload.html.port} / HTTP</code><ChevronRight size={15} /></button><div><Database size={16} /><strong>Aplicacion web</strong><code>{payload.web.port} → {payload.web.internalPort}</code></div></div>
      </section>}
      <footer className="workspace-footer"><span>VECIANA / MUNICIPIO FICTICIO</span><span>OpenMetadata externo <ExternalLink size={11} /></span></footer>
    </main>
    {(confirmation || selectedRow) && <div className="modal-backdrop" onClick={() => { if (!busy) { setConfirmation(null); setSelectedRow(null); } }}><section className="modal" role="dialog" aria-modal="true" aria-label={confirmation ? 'Confirmar cambio' : 'Detalle del registro'} onClick={event => event.stopPropagation()} onKeyDown={event => { if (event.key === 'Escape' && !busy) { setConfirmation(null); setSelectedRow(null); } if (event.key === 'Tab') { const focusable = Array.from(event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input')); const first = focusable[0]; const last = focusable.at(-1); if (event.shiftKey && document.activeElement === first && last) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last && first) { event.preventDefault(); first.focus(); } } }}><header><span className="eyebrow">{confirmation ? `${labels[dbId]} / CAMBIO CONTROLADO` : `${table} / REGISTRO`}</span><button autoFocus className="icon-button" title="Cerrar" aria-label="Cerrar dialogo" disabled={busy} onClick={() => { setConfirmation(null); setSelectedRow(null); }}><X size={19} /></button></header>{confirmation ? <><h2>{confirmation.label}</h2><p>{confirmation.detail}</p><pre className="sql-preview">{confirmation.sql || confirmation.preview}</pre><div className="notice"><AlertTriangle size={16} /><span>{confirmation.id === 'reset-all' ? 'Modifica las cuatro fuentes. No hay rollback global.' : db?.type === 'html' ? 'Modifica la tabla publicada en la web Escoles.' : dbId === 'tributos' && ['add-column', 'change-type', 'reset'].includes(confirmation.id) ? 'MySQL aplica DDL con autocommit. No hay rollback global.' : 'Modifica la base real del laboratorio.'}</span></div>{confirmation.id === 'reset-all' && <label className="reset-label">Escribe RESTAURAR TODO<input value={resetText} onChange={event => setResetText(event.target.value)} /></label>}{error && <div role="alert" className="error">{error}</div>}<footer><button className="text-button" disabled={busy} onClick={() => setConfirmation(null)}>Cancelar</button><button className={`primary-button ${confirmation.id.includes('reset') ? 'destructive' : ''}`} disabled={busy || confirmation.id === 'reset-all' && resetText !== 'RESTAURAR TODO'} onClick={execute}><Play size={16} />{busy ? 'Ejecutando...' : 'Confirmar y ejecutar'}</button></footer></> : <><h2>Registro {selectedRow.id ?? ''}</h2><dl className="record-details">{Object.entries(selectedRow).map(([key, value]) => <div key={key}><dt>{key}</dt><dd><Cell value={value} /></dd></div>)}</dl></>}</section></div>}
  </div>;
}